### ISSUE TITLE
java.lang.IllegalStateException: Not a JSON Array

### ISSUE THREAD

**Issue by harti2006** [microsoft/kiota-java#1147]
Hi, I upgraded my project to the latest microsoft-graph version (6.5.1), which included a version bump of microsoft-kiota-serialization-json from 1.0.4 to 1.1.2. Suddenly a simple graph query started to fail:

```
java.lang.IllegalStateException: Not a JSON Array: {"displayName":"My Group","id":"11111111-1111-1111-1111-111111111111    ","members@delta":[{"@odata.type":"#microsoft.graph.user","id":"22222222-2222-2222-2222-222222222222"}]}
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:117) ~[gson-2.10.1.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:167) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getUntypedValue(JsonParseNode.java:245) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.tryGetAnything(JsonParseNode.java:317) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:299) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.lambda$getCollectionOfObjectValues$1(JsonParseNode.java:195) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:175) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getCollectionOfObjectValues(JsonParseNode.java:195) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.graph.groups.delta.DeltaGetResponse.lambda$getFieldDeserializers$0(DeltaGetResponse.java:36) ~[microsoft-graph-6.5.1.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:297) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:296) ~[microsoft-kiota-http-okHttp-1.1.2.jar:?]
	at com.microsoft.graph.groups.delta.DeltaRequestBuilder.get(DeltaRequestBuilder.java:58) ~[microsoft-graph-6.5.1.jar:?]
```

I'm querying the MicrosoftGraph with the following URL: `https://graph.microsoft.com/v1.0/groups/delta()?$select=id,displayName,members`. In code this looks like:
```kotlin
graph.groups().delta().get { request -> request.queryParameters.select = listOf("id", "displayName", "members").toTypedArray() }
```

I believe the problem was introduced with this change:
https://github.com/microsoft/kiota-java/commit/823f268ddcdfaf8535eba2bbec73db72770fe420?diff=unified&w=0#diff-4d5d58f2ee19b617f52c3d365d9b8bf2665ca6d4bc28aedb74e755c2e5ed5c4dR296

Before: https://github.com/microsoft/kiota-java/blob/65a1eb9c5024b248071c7807bb816d677d68f8bd/components/serialization/json/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java#L296

After: https://github.com/microsoft/kiota-java/blob/823f268ddcdfaf8535eba2bbec73db72770fe420/components/serialization/json/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java#L296

**Comment by andrueastman** [comment]
Thanks for raising this @harti2006 

This is a regression from https://github.com/microsoft/kiota-java/pull/1070. And should be addressed via https://github.com/microsoft/kiota-java/pull/1148
