### ISSUE TITLE
ApiException and ODataError cannot be serialized, even though they implement Serializable via Throwable

### ISSUE THREAD

**Issue by poschi3** [microsoft/kiota-java#1560]
The classes `ApiException` and `ODataError` extends from `Throwable` which implements `Serializable`. So both must be `Serializable`. Unfortunately each has a member which does not implement `Serializable` so both can not be serialized. A `NotSerializableException`is thrown.

In `ApiException` there is the `ResponseHeaders` and on `ODataError` there is the `BackingStore` and `Pair<A, B>` which does not implement `Serializable`.

Could you please make them implement `Serializable` to fulfill the contract from `Throwable`?

## Example code

```java
final ByteArrayOutputStream bos = new ByteArrayOutputStream();
ObjectOutputStream out = null;
out = new ObjectOutputStream(bos);
out.writeObject(new ApiException()); // Alternative: new ODataError();
```

```
java.io.NotSerializableException: com.microsoft.kiota.ResponseHeaders
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
	at x.x.x.x.x.ApiExceptionTest.testApiException(ApiExceptionTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by baywet** [comment]
Hi @poschi3 
Thank you for using kiota and for reaching out.
As far as I understand the only requirements for a class to be serializable:
- implements Serializable (marker interface)
- all fields are primitive or implement Serializable

Am I missing anything?

If so, the only thing missing is for the response headers to implement Serializable as the stack trace you've provided indicates. And this could be achieved through [marking the parent CaseInsensitiveMap](https://github.com/microsoft/kiota-java/blob/645f261f372838843a281c2ffdca700d2fe4be0f/components/abstractions/src/main/java/com/microsoft/kiota/CaseInsensitiveMap.java#L19)

Is this something you'd like to submit a pull request for provided some guidance?

**Comment by poschi3** [comment]
HI @baywet 
Thank you for your answer.

I tested it with marking CaseInsensitiveMap and it worked. This part in fact contains only one `HashMap<String, HashSet<String>>` which is all Serializable.

After I've done this I got in case of `ODataError` an error for the `InMemoryBackingStore`:

```
java.io.NotSerializableException: com.microsoft.kiota.store.InMemoryBackingStore
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
	at x.x.x.x.x.ApiExceptionTest.testODataError(ApiExceptionTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

Marking InMemoryBackingStore as Serializable lead to problem with `Pair<A, B>`. Marking this also as Serializable solved problem in my testcase. But I'm not sure if this is "legal", because InMemoryBackingStore contains this members with type Object:

https://github.com/microsoft/kiota-java/blob/645f261f372838843a281c2ffdca700d2fe4be0f/components/abstractions/src/main/java/com/microsoft/kiota/store/InMemoryBackingStore.java#L51-L52

I don't know which Objects are there and if they are serializable.

**Comment by baywet** [comment]
Thank you for the additional information.

I should be safe to mark it as well as far as I understand. We're using object because it can be a mix of primitive types, Parsable, collection of primitive types, collection of Parsable.

It'd require to mark Parsable as Serializable as well though, I'm not sure what the side effects of that could be, but it'd be potentially large.
Is there a way to "mark a property to be ignored"?

**Comment by poschi3** [comment]
There is a `transient` keyword, but I have no experience with it: https://stackoverflow.com/a/910522

**Comment by poschi3** [comment]
Yes, that makes sense to me :-)

**Comment by baywet** [comment]
Is this something you'd like to submit a pull request for provided some guidance?

**Comment by poschi3** [comment]
@baywet I prototyped something but I'm not sure if it's ready. If I find some spare time I can make a pull request

**Comment by baywet** [comment]
Don't hesitate to submit your pull request as a draft once it's clean enough. It'll make a base for discussion.
