### ISSUE TITLE
com.microsoft.kiota.serialization.ParseNodeFactoryRegistry throws RuntimeException if service returns status code 503 with unexpected content type

### ISSUE THREAD

**Issue by etcoyvindf** [microsoft/kiota-java#1683]
Situation and background:
The Microsoft Graph API had some issues some days ago, where some calls to the API would return HTTP status code 503, with some html error message.

During this time, our use of the Graph API SDK, which in turn uses Kiota, lead to several application level crashes, because of uncaught RuntimeExceptions was propagated up the call stack from Kiota.

My observations, based on my understanding of the code:
The source of the exception, ParseNodeFactoryRegistry  method getParseNode will attempt to find a parser for an expected content type. 
In the case of Graph API, we expect JSON, so we only set up factories to handle that. 

When the Graph API has an issue/downtime/whathaveyou, the method finds no factory to handle the response, and throws a RuntimeException directly.

Straight forward, I feel theres' two possible solutions.
1. Make getParseNode throw ApiException, which is a bit safer to try/catch than a pure "catch all" RuntimeException
2. Add a special case content type text/html factory that handles special error page responses, which might be in scope only for the graph api sdk.

With limited knowledge of how easy a custom factory is as an end user of MS Graph SDK, we feel forced to stop catching ApiException, and start catching RuntimeExceptions instead, hoping that no other runtime exceptions gets thrown and swallowed by our logic.

**Comment by etcoyvindf** [comment]
link to the method that throws the exception: https://github.com/microsoft/kiota-java/blob/0cd6b6d8a3263c6cc2d1d1fe6b2358c054da46e0/components/abstractions/src/main/java/com/microsoft/kiota/serialization/ParseNodeFactoryRegistry.java#L56C8-L57C97

Stacktrace from our log:

java.lang.RuntimeException: Content type text/html does not have a factory to be parsed
        at com.microsoft.kiota.serialization.ParseNodeFactoryRegistry.getParseNode(ParseNodeFactoryRegistry.java:56)
        at com.microsoft.kiota.http.OkHttpRequestAdapter.getRootParseNode(OkHttpRequestAdapter.java:582)
        at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:649)
        at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:280)
        at com.microsoft.graph.users.item.events.item.EventItemRequestBuilder.get(EventItemRequestBuilder.java:176)
at com.microsoft.graph.users.item.events.item.EventItemRequestBuilder.get(EventItemRequestBuilder.java:176)
.. internal code folllows here,  `graphClient.me().events().byEventId(id).get(rc -> addStandardOutlookRequestHeaders(rc.headers));`

**Comment by baywet** [comment]
Hi @etcoyvindf 
Thank you for using the SDK and for reaching out.

Could you please provide which endpoint and operation you are using? The service should NOT be replying with html pages and we'll want to report that to the service team. If you could also include client request ids and timestamps, it'd be great.

Since Api exception derives from runtime exception, it's unchecked, which means there would be no impact to the method prototype.

That class was originally designed to represent errors coming back from the service itself, and one could argue this is a client exception not being able to parse the result due to lack of support for a given format. What would you think about adding a "ClientException" similar to the API exception?

**Comment by Ndiritu** [comment]
@baywet Wondering whether the new `ClientException` type should be the default wrapper type we expose for all internal client-related exceptions. We still throw a bunch of IllegalArgumentExceptions and RuntimeExceptions in different layers of the Kiota code

**Comment by baywet** [comment]
For the runtime exceptions probably, for the argument validation, most likely not. Since it's a standard practice to use those exception types.

**Comment by coinzz** [comment]
We get the same error frequently on different graph requests using the java sdk com.microsoft.graph:microsoft-graph:6.67 and because of that we don't know what the actual error is, since it's content cannot be parsed by the sdk 🥲

For example on:
- com.microsoft.graph.users.item.calendar.events.EventsRequestBuilder.get(EventsRequestBuilder.java:91)
- com.microsoft.graph.users.item.sendmail.SendMailRequestBuilder.post(SendMailRequestBuilder.java:58)
- com.microsoft.graph.users.item.calendarview.CalendarViewRequestBuilder.get(CalendarViewRequestBuilder.java:68)

We do those requests a lot and only a small amount face these issues, where we now can't identify the root cause.
